app1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('system.urls')),
    url(r'^admin/', admin.site.urls),
]

system/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'system'
urlpatterns = [
        url(r'^accounts/new/$', views.UserCreate.as_view(), name='register'),
        url(r'^accounts/edit/$', views.register, name='user_edit'),
        url(r'^accounts/', include('django.contrib.auth.urls')),

        url(r'^dashboard/$', views.dashboard, name='dashboard'),

        url(r'^manage/accounts/$', views.UserList.as_view(), name='user_list'),
        url(r'^manage/accounts/new$', views.StaffCreate.as_view(), name='staff_register'),
        url(r'^manage/accounts/delete/(?P<pk>[0-9]+)/', views.UserDelete.as_view(), name='user_del'),
        url(r'^manage/accounts/(?P<pk>[0-9]+)/', views.UserDetail.as_view(), name='user_detail'),

        url(r'^messages/new/', views.SendMessage.as_view(), name='send_msg'),

        url(r'^item/new/',views.NewItem.as_view(),name='post_item'),
        url(r'^add/(?P<id>[0-9]+)/',views.add,name='add'),

        url(r'^$', views.index, name='home'),
        url(r'^logout/$', views.logout_view, name='logout')
    ]

system/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from system import models

#Form for an Admin Registration Form
class AdminRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    date_of_birth = forms.DateField()
    phone_number = forms.CharField()
    mail_address = forms.CharField(widget=forms.Textarea)
    role = forms.ChoiceField(
            choices = models.Registration.ROLE_TYPE_CHOICES
            )

    #Meta and save overwrite default user creation form to include email, first name, and last name
    class Meta:
        model = models.User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    #Meta and save overwrite default user creation form to include email, first name, and last name
    def save(self, commit=True):
        user = super(AdminRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        reg = models.Registration()
        reg.date_of_birth = self.cleaned_data['date_of_birth']
        reg.phone_number = self.cleaned_data['phone_number']
        reg.mail_address = self.cleaned_data['mail_address']
        reg.role = self.cleaned_data['role']

        if commit:
            user.save()
            reg.user = user
            reg.save()
        return user
    
#Form for a Patient Registration Form
class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    date_of_birth = forms.DateField()
    phone_number = forms.CharField()
    mail_address = forms.CharField(widget=forms.Textarea)

    ChOI=(
        ('BU','Buyer'),
        ('SE','Seller')
    )

    role = forms.ChoiceField(choices=ChOI,required=True)

    #Meta and save overwrite default user creation form to include email, first name, and last name
    class Meta:
        model = models.User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    #Meta and save overwrite default user creation form to include email, first name, and last name
    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        reg = models.Registration()
        reg.date_of_birth = self.cleaned_data['date_of_birth']
        reg.phone_number = self.cleaned_data['phone_number']
        reg.mail_address = self.cleaned_data['mail_address']

        if commit:
            user.save()
            
        reg.user = user
        if commit:
            reg.save()
        return user

#Form for a Patient Registration Form
class Cart(UserCreationForm):
    timestamp=forms.CharField(max_length=30)

    #Meta and save overwrite default user creation form to include email, first name, and last name
    class Meta:
        model = models.Cart
        fields =('name','description','condition','price','quantity')

    def save(self, commit=True):
        user = super(Cart, self).save(commit=False)
        self.object=form.save(commit=False)
        self.object.buyer=User
        self.object.save()
        return super(edit.ModelFormMixin,self).form_valid(form)

system/views.py
from django import forms
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse_lazy,reverse
from django.views.generic import edit, list, DetailView 
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.template import loader, Context
from . import forms
from . import models

from django.template import RequestContext

# User Generic Views.
class UserCreate(edit.CreateView):
    model = models.User
    form_class = forms.MyRegistrationForm
    template_name = "system/registration_form.html"
    success_url = reverse_lazy('system:dashboard')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        logout(self.request)
        return super(UserCreate, self).form_valid(form)

def add(request,id):
    if request.method=='POST':
        item=get_object_or_404(models.Item,pk=id)
        cart=models.Cart
        buyer=item.user
        user=item.user
        name=item.name
        description=item.description
        condition=item.condition
        price=item.price
        quantity=item.quantity#
        allItems=models.Item.objects.all()
        AddCart.as_view()(request)

        objects=models.Cart(name=name,description=description,condition=condition, price=price,quantity=quantity)
        objects.save()
        cartall=models.Cart.objects.all()
        item.save()
        #cartall.save()

        context=RequestContext(request)
    
        #return render(request,'system/buyer_dashboard.html',{"items"allItems)
        return redirect('/dashboard')

#View that lets an admin create other staff accounts
@method_decorator(login_required, name='dispatch')
class StaffCreate(edit.CreateView):
    model = models.User
    form_class = forms.AdminRegistrationForm
    template_name = "system/registration_form.html"
    success_url = reverse_lazy('system:dashboard')

    #Checks to make sure the user the form is being sent to is an admin
    def dispatch(self, request):
        user = get_object_or_404(models.Registration, user=request.user)
        if user.role == models.Registration.ADMIN:
            return super(StaffCreate, self).dispatch(request)
        else:
            return HttpResponseForbidden()

@login_required
def request_page(request):
    if(request.GET.get('AddToCart')):
        model=models.Cart
        #obj=Items.objects.filter(name=request.GET.get(
        fields=['name','description','condition','price','quantity']
    return render(request,'system/items_2.html')

#View for post-account-creation patients to create or update their individual information
# Redirects to proper view based on user role.
@login_required
def register(request):
    user = get_object_or_404(models.Registration, user=request.user)
    if user.role == models.Registration.SELLER:
        return UserEdit.as_view()(request)
    else:
        return StaffEdit.as_view()(request)
    return HttpResponseForbidden()

#View for post-account-creation patients to create or update their individual information
class UserEdit(edit.UpdateView):
    model = models.Registration
    fields = ['primary_care', 'date_of_birth', 'phone_number', 'mail_address']
    template_name = "system/registration_profile_info.html"
    success_url = reverse_lazy('system:dashboard')

    #Retrieves the user from the database
    def get_object(self, queryset=None):
        return get_object_or_404(models.Registration, user=self.request.user)

#Form for post-account-creation staff to create or update their individual information
class StaffEdit(edit.UpdateView):
    model = models.Registration
    fields = ['date_of_birth', 'phone_number', 'mail_address']
    template_name = "system/registration_profile_info.html"
    success_url = reverse_lazy('system:dashboard')

    #Retrieves the user from the database
    def get_object(self, queryset=None):
        return get_object_or_404(models.Registration, user=self.request.user)

#Gets a list of all registered users
@method_decorator(login_required, name='dispatch')
class UserList(list.ListView):
    #Defining Parameters
    model = models.Registration
    queryset = models.Registration.objects.all()

    #Performs the request with the given parameters
    def get(self, request):
        user = get_object_or_404(models.Registration, user=request.user)
        if user.role == models.Registration.ADMIN:
            return super(UserList, self).get(request)
        else:
            return HttpResponseForbidden()

#Displays the details of a single user
@method_decorator(login_required, name='dispatch')
class UserDetail(DetailView):
    model = models.Registration

    #Performs the request with the given parameters
    def get(self, request, pk):
        user = get_object_or_404(models.Registration, user=request.user)
        if user.role == models.Registration.ADMIN:
            return super(UserDetail, self).get(request, pk)
        else:
            return HttpResponseForbidden()

#View to delete a user
@method_decorator(login_required, name='dispatch')
class UserDelete(edit.DeleteView):
    model = models.User
    success_url = reverse_lazy("system:dashboard")

    #Checks to see if the user is admin before deleting the user
    def dispatch(self, request, pk):
        user = get_object_or_404(models.Registration, user=request.user)
        if user.role == models.Registration.ADMIN:
            return super(UserDelete, self).dispatch(request, pk)
        else:
            return HttpResponseForbidden()

#View for the dashboard, each dashboard is generated separately depending on what role the user is
@login_required
def dashboard(request):
    user = get_object_or_404(models.Registration, user=request.user)
    messages = models.Message.objects.filter(recipient=user).order_by('-timestamp')
    items=models.Item.objects.filter(poster=request.user).order_by('-timestamp')
    cart=models.Cart.objects.all()
    if user.role == models.Registration.SELLER:
        appt = models.Appointment.objects.filter(seller=user)
        buyers=models.Registration.objects.filter(role='BU')

        template_name = "system/seller_dashboard.html"
        return render(request, template_name, context={'user':user, 'appts':appt, 'byrs':buyers, 'msgs':messages,'tems':items})
    elif user.role == models.Registration.BUYER:
        appt = models.Appointment.objects.filter(buyer=user)
        template_name = "system/buyer_dashboard.html"
        items=models.Item.objects.all()
        return render(request, template_name, context={'user':user, 'appts':appt, 'msgs':messages,'tems':items,'cart':cart})
    elif user.role == models.Registration.ADMIN:
        system_act = models.Activity.objects.all().order_by('-timestamp')
        users = models.Registration.objects.all()
        stats = GenerateStatisticsContext(request)
        template_name = "system/admin_dashboard.html"
        return render(request, template_name, context={'user':user, 'sys':system_act, 'users':users, 'msgs':messages, 'stat':stats})

    return HttpResponseForbidden()

def add_cart(request):
    context=RequestContext(request)
    if request.method=='post':
        form=CartForm(request.POST)
    return render_to_response('system/add_cart.html',{'form':form},context)

#Home page view
def index(request):
    return render(request, "system/home.html")

#Logout view
def logout_view(request):
    logout(request)
    return redirect('/accounts/login/')

#View to send a message
@method_decorator(login_required, name='dispatch')
class SendMessage(edit.CreateView):
    model = models.Message
    fields = ['recipient', 'text']
    template_name = "system/message_form.html"
    success_url = reverse_lazy("system:dashboard")

    def form_valid(self, form):
        sender = models.Registration.objects.get(user=self.request.user)
        self.object = form.save(commit=False)
        self.object.sender = sender
        self.object.save()
        return super(edit.ModelFormMixin, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class NewItem(edit.CreateView):
    model=models.Item
    fields=['name','description','condition','price','quantity']
    template_name="system/item_form.html"
    success_url=reverse_lazy("system:dashboard")

    def form_valid(self,form):
        user=self.request.user
        self.object=form.save(commit=False)
        self.object.poster=user
        self.object.save()
        return super(edit.ModelFormMixin,self).form_valid(form)

@method_decorator(login_required,name='dispatch')
class AddCart(edit.CreateView):
    model=models.Cart
    fields=['name','description','condition','price','quantity']
    success_url=reverse_lazy("system:dashboard")
    def form_valid(self,form):
        buyer=self.request.user
        self.object=form.save(commit=False)
        self.object.save()
        return super(edit.ModelFormMixin,self).form_valid(form)

#Gets a list of all patients for a doctor
@method_decorator(login_required, name='dispatch')
class buyerList(list.ListView):
    #Defining Parameters
    model = models.Registration
    queryset = models.Registration.objects.filter(role=models.Registration.BUYER)
    template_name = "system/patient_list.html"

    #Performs the request with the given parameters
    def get(self, request):
        user = get_object_or_404(models.Registration, user=request.user)
        if user.role == models.Registration.SELLER:
            return super(PatientList, self).get(request)
        else:
            return HttpResponseForbidden()

#Generates basic statistics and returns them as context to be rendered
def GenerateStatisticsContext(request):
    stats = Context()
    buyers = models.Registration.objects.filter(role=models.Registration.BUYER)

system/templates/system/admin_dashboard.html
{% extends "layout.html" %}

{% block content %}
    <p style='float:left; padding:10px'>[Admin] {{ user.user.username }}</p>
    <a href='{% url 'system:logout' %}' class="btn btn-primary">Logout</a>
    <div class="row">
        <h2>Dashboard</h2>
        <div class="col-md-4">
            <h3>User List</h3>
            <a href="{% url 'system:staff_register' %}">Create Account</a>
            {% include "system/user_list.html" %}
            &nbsp;
            <h3>System Statistics</h3>
            <ul class="list-group">
                <li class="list-group-item">Total Number of Buyers: {{ stat.tot_pat }}</li>
                <li class="list-group-item">Total Sellers: {{ stat.tot_doc }}</li>
                <li class="list-group-item">Buyer to Seller ratio: {{ stat.stf_rat }}</li>
            </ul>

            {% include "system/messages.html" %}
        </div>
        <div class="col-md-8">
            {% include "system/system_logs.html" %}
        </div>
    </div>
{% endblock %}

system/templates/system/buyer_dashboard.html
{% extends "layout.html" %}

{% block content %}
    <p style='float:left; padding:10px'>[Buyer] {{ user.user.username }}</p>
    <a href='{% url 'system:logout' %}' class="btn btn-primary">Logout</a>
    <div class="row">
        <h2>Dashboard</h2>
        <div class="col-md-4 col-sm-4">
            {% include "system/buyer_info.html" %}
        </div>
        <div class="col-md-8 col-sm-8">
            {% include "system/messages.html" %}
        </div>
        <div class="col-md-4 col-sm-4">
            {% include "system/cart.html" %}
        </div>
    </div>
    <div>
        {% include "system/items_2.html" %}
    </div>
{% endblock %}

system/templates/system/cart.html
<h3>Cart</h3>
<ul class="list-group">
{% for ca in cart %}
    <li class="list-group-item">name={{ca.name}}, quantity={{ ca.quantity }}, condition= {{ ca.condition }}, price={{ca.price}}</li>
{% empty %}
    <li class="list-group-item">You have no items in cart</li>
{% endfor %}
</ul>

system/templates/system/cart_form.html
{% extends "layout.html" %}

{% block content %}
    <h3>Item</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Post" />
    </form>
    <form action="/dashboard/" method="get">
        <input class="btn btn-primary" type="submit" value="Cancel"/>
    </form>
{% endblock %}

system/templates/system/item_form.html
{% extends "layout.html" %}

{% block content %}
    <h3>Item</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Post" />
    </form>
    <form action="/dashboard/" method="get">
        <input class="btn btn-primary" type="submit" value="Cancel"/>
    </form>
{% endblock %}

system/templates/system/items.html
<h3>Items</h3>
<a href="{% url 'system:post_item' %}">New Item</a>
<ul class="list-group">
{% for item in tems %}
    <li class="list-group-item">name= {{ item.name }}, price= {{ item.price }}, condition= {{item.condition}}, quantity={{item.quantity}}, description= {{item.description}}</li>
{% empty %}
    <li class="list-group-item">You have no items</li>
{% endfor %}
</ul>

system/templates/system/items_2.html
<h3>Items</h3>
<ul class="list-group">
{% for item in tems %}
    <li class="list-group-item">name= {{ item.name }}, description= {{item.description }}, condition= {{item.condition}}, quantity= {{ item.quantity }}, price= {{ item.price }}  
    <label for="quan">Quantity: </label>
    <input type="number" step="any" name="quan" value="0" max="{{item.quantity}}" min="0" />

 
    <form method="post" action="{% url 'system:add' item.id %}">
        {% csrf_token %}
        <input type="submit" name="submit" value="Add to Cart" />
    </form>

</li>

{% empty %}
    <li class="list-group-item">You have no items</li>
{% endfor %}
</ul>

system/templates/system/message_form.html
{% extends "layout.html" %}

{% block content %}
    <h3>Send Message</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Send" />
    </form>
    <form action="/dashboard/" method="get">
        <input class="btn btn-primary" type="submit" value="Cancel"/>
    </form>
{% endblock %}

system/templates/system/messages.html
<h3>Messages</h3>
<a href="{% url 'system:send_msg' %}">New Message</a>
<ul class="list-group">
{% for msg in msgs %}
    <li class="list-group-item">{{ msg.sender }}: {{ msg.text }}</li>
{% empty %}
    <li class="list-group-item">You have no new messages</li>
{% endfor %}
</ul>

system/templates/system/registration_detail.html
{% extends "layout.html" %}
{% block content %}
<div class="registration">
    [{{ registration.id }}] {{ registration }} - {{ registration.role }}
</div>
{% endblock %}

system/templates/system/registration_list.html
{% extends "layout.html" %}
{% block content %}
{% for registration in object_list %}
    <div class="registration">
        [{{ registration.id }}] {{ registration }} - {{ registration.role }}
    </div>
{% empty %}
    No users.
{% endfor %}
{% endblock %}

system/templates/system/registration_profile_info.html
{% extends "layout.html" %}

{% block content %}
    <h3>Registration:</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Save" />
    </form>
{% endblock %}

system/templates/system/sell.html
<h3>Items</h3>
<a href="{% url 'system:post_item' %}">New Item</a>
<ul class="list-group">
{% for item in tems %}
    <li class="list-group-item">{{ item.name }}, quantity={{ item.quantity }}</li>
{% empty %}
    <li class="list-group-item">You have no items</li>
{% endfor %}
</ul>

system/templates/system/system_logs.html
<h3 style="text-align: center;">System Activity</h3>
<ul class="list-group">
{% for log in sys %}
    <li class="list-group-item">[{{ log.timestamp }}] | Type: {{ log.activity_type }} | User: {{ log.user_responsible }} | {{ log.description }}
{% empty %}
    <li class="list-group-item">There has been no activity in the system logs.</li>
{% endfor %}
</ul>